### ISSUE TITLE
Domino effect

### ISSUE THREAD

**Issue by Arne-Berner** [andriyDev/dodgy#12]
Instead of trying to occupy the space they are already occupying, they will move very far away from each other when something comes near them quite slow. That way there will be some weird domino effect, where they push each other away a lot and won't come to a stop even with heavy de-accelerating (aka. setting the velocity to 0 after moving)

**Comment by andriyDev** [comment]
I'm not understanding what you mean. An example would be helpful! If another agent comes too close (which is determined from the agent radii and the time horizon), the agents will try to avoid each other, even if one agent has a preferred velocity of zero.

If you want stopped agents not to move, you can set their avoidance responsibility to zero. Then they won't try to avoid anything and the moving agent will do all the avoidance.

**Comment by Arne-Berner** [comment]
I've read the paper and I would agree with you, although with enough agents there will be little movements of avoiding each other and probably due to floats being used, they keep pushing each other endlessly, because there will always be at least one unit, pushing other units again. So a whole group that should've settled, will now keep on pushing each other forever. (Although I might as well mitigate that, if the velocity goes towards zero, that I just set it to zero)

**Comment by andriyDev** [comment]
If the goals of each agent are too close to each other (within agent radius), then yes the agents will never settle. However otherwise, once the agent reaches their goal, their preferred velocity should be zero, so eventually they should settle (because the time horizon will trivially be satisfied).
