### ISSUE TITLE
re-exporting glam::Vec2

### ISSUE THREAD

**Issue by av-maurits** [andriyDev/dodgy#13]
Currently the lib.rs of this crate does not re-export its dependency on glam:Vec2. This means that any user of the crate has to add glam to its toml manually. Besides being inconvenient, this can result in problems. Currently glam v0.25.0 is out, while dodgy depends on  v0.24.0. This results in a very uninituitive error that the types seem equal but are actually distinct types. This occurs as you are trying to provide a v0.25.0 Vec2 to an interface that expects v0.24.0 (implying they are different types, though being named equal and originating from the same crate). 

The solution to this problem is to simply add pub use glam::Vec2 to your lib.rs, re-exporting the dependency to your own distinct type. This way, any user can simply use dodgy::Vec2 and omit the explicit use of glam altogether.

**Comment by andriyDev** [comment]
Ahhh I didn't realize this! Thank you for this. I'll make a PR and upgrade the glam version.
