### ISSUE TITLE
3D?

### ISSUE THREAD

**Issue by robinei** [andriyDev/dodgy#18]
The C++ version had a 3D variant. Are you interested in supporting that?

**Comment by andriyDev** [comment]
I personally don't have much interest haha. Perhaps it could be supported as a nested module containing just 3d stuff?

What's your use case, for my own learning? I feel like needing real 3d avoidance is rare, and in those cases something akin to boids might work better.

**Comment by andriyDev** [comment]
That's a pretty convincing use case! I'll see what I can do. It might be gross to have a 2d module and a 3d module (feature flagged), but I think it may be worth it. I'm also hoping the 3d version shares some code with the 2d version haha

**Comment by robinei** [comment]
That would be great! I guess some things might get more complex. Obstacle volumes for one. Not sure if spheres around points would be natural to implement, but I think it would be what I need at least (looking to make something space based). I love the non-intrusive bring-your-own spatial lookup approach you support, btw.

**Comment by andriyDev** [comment]
Ah yes I think that's where the C++ version gave up. FWIR, the C++ version didn't have support for obstacles in 3D. Even if we were to support it, it would probably be incredibly expensive performance-wise.

That said, we can just make obstacles that are just agents that never move and that might work!

**Comment by andriyDev** [comment]
@robinei would you mind reviewing #20? Or at the very least testing it out? I'd just like to make sure it works for you. Sorry it took so long!
